---
- name: Deploy Flask Application to New EC2 Instance
  hosts: new_ec2_instance
  become: true

  tasks:
    - name: Check if Python 3 is installed
      command: python3 --version
      register: python_version
      ignore_errors: true
      changed_when: false

    - name: Install Python 3 if not installed
      dnf:
        name: python3
        state: present
      when: python_version.rc != 0

    - name: Check if Docker is installed
      command: docker --version
      register: docker_version
      ignore_errors: true
      changed_when: false

    - name: Install Docker if not installed
      dnf:
        name: docker
        state: present
      when: docker_version.rc != 0

    - name: Start Docker service if not running
      service:
        name: docker
        state: started

    - name: Install Python 3 pip package
      dnf:
        name: python3-pip
        state: present

    - name: Install Docker Python library
      pip:
        name: docker
        state: present
        extra_args: "--ignore-installed"

    - name: Check if port 5000 is in use
      shell: "netstat -tuln | grep ':5000 '"
      register: port_check
      ignore_errors: true

    - name: Stop process using port 5000
      shell: "kill -9 $(lsof -t -i:5000)"
      when: port_check.rc == 0

    - name: Pull Docker image
      docker_image:
        name: "{{ docker_image_name }}"
        source: pull

    - name: Run Docker container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image_name }}"
        state: started
        ports:
          - "{{ host_port }}:{{ flask_app_port }}"
